"""new img

Revision ID: 2092885ec80b
Revises: 21b6c6ede2c3
Create Date: 2024-08-30 18:53:44.244221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2092885ec80b'
down_revision = '21b6c6ede2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=140), nullable=False))
        batch_op.create_index(batch_op.f('ix_artist_img'), ['img'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_img'))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
