"""hello

Revision ID: 21b6c6ede2c3
Revises: 
Create Date: 2024-08-30 15:49:30.462022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b6c6ede2c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('insta', sa.String(length=64), nullable=False),
    sa.Column('spotify', sa.String(length=64), nullable=False),
    sa.Column('twitter', sa.String(length=64), nullable=False),
    sa.Column('facebook', sa.String(length=64), nullable=False),
    sa.Column('booking', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_booking'), ['booking'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_facebook'), ['facebook'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_insta'), ['insta'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_spotify'), ['spotify'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_twitter'), ['twitter'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_username'), ['username'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('spotify', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_spotify'), ['spotify'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loc', sa.String(length=140), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_venue_link'), ['link'], unique=False)
        batch_op.create_index(batch_op.f('ix_venue_loc'), ['loc'], unique=False)
        batch_op.create_index(batch_op.f('ix_venue_time'), ['time'], unique=False)

    op.create_table('artist_venue',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_venue')
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_time'))
        batch_op.drop_index(batch_op.f('ix_venue_loc'))
        batch_op.drop_index(batch_op.f('ix_venue_link'))
        batch_op.drop_index(batch_op.f('ix_venue_date'))

    op.drop_table('venue')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_spotify'))

    op.drop_table('user')
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_username'))
        batch_op.drop_index(batch_op.f('ix_artist_twitter'))
        batch_op.drop_index(batch_op.f('ix_artist_spotify'))
        batch_op.drop_index(batch_op.f('ix_artist_name'))
        batch_op.drop_index(batch_op.f('ix_artist_location'))
        batch_op.drop_index(batch_op.f('ix_artist_insta'))
        batch_op.drop_index(batch_op.f('ix_artist_facebook'))
        batch_op.drop_index(batch_op.f('ix_artist_description'))
        batch_op.drop_index(batch_op.f('ix_artist_booking'))

    op.drop_table('artist')
    # ### end Alembic commands ###
